from django.apps import AppConfig


class ExceptionConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'exception'
